### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by filmdc** [sdj0/fire-1099#19]
Checking this out as a backup plan to our current system, but can't get it to run:
```
# fire-1099 1099_MISC_schematest.json --output outputminimal.ascii
Traceback (most recent call last):
  File "/usr/local/bin/fire-1099", line 7, in <module>
    from fire.translator import cli
  File "/usr/local/lib/python2.7/dist-packages/fire/translator/__init__.py", line 5, in <module>
    from .translator import cli
  File "/usr/local/lib/python2.7/dist-packages/fire/translator/translator.py", line 241
    data["end_of_payer"]["payment_amount_" + code] = f"{total:0>18}"
                                                                                                              ^
```

Using Ubuntu 18.04.5 LTS
Python 2.7.17
pip 20.3.4

**Comment by mreddy614** [comment]
Unable to execute the code in Windows. Below is error:

C:\Python34\fire-1099\fire>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import translator
>>> input_path = "spec/valid_minimal_MISC.json"
>>> output_path = "output_file.ascii"
>>> translator.run(input_path, output_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'translator' has no attribute 'run'
>>>

**Comment by sdj0** [comment]
Thanks for raising these! And for you patience with my slow response - I've been meaning to investigate but haven't had the chance to regrettably, on account of the day job.

At a glance, my suspicion is that the test data `1099_MISC_schematest.json` is out of date with the new 2021 schema changes, which @brelkl incorporated in https://github.com/sdj0/fire-1099/commit/27b133dfd791465a8baf8970e3f5e0d2b19168da and I merged.

I'll try to look closer in the next few days, but in the meantime you may be able to get a run working by updating the JSON to match the commit above.

**Comment by brelkl** [comment]
If you'd like @sdj0, I can take a look at this issue. I can't reproduce it with any of the sample files in the spec/data/ directory, but I do get an error if I use one of the actual schema files as input. But that is expected behavior, right? So if a schema was used I'd expect an error--and if not I'd need to reference the json file that's causing the issue. In any case, I can update the schemas (and the spec/data/valid*.json files) to reflect all the possible payee rows, if that would be helpful.

**Comment by sdj0** [comment]
Just now taking a closer look at these issues:

@filmdc if you're trying to run this on a _schema_ file, this error is expected (as @brelkl pointed out). The JSON schema files like those in /fire/schema define the attributes that an input JSON file should have; they aren't input files themselves. If you're looking for sample inputs, take a look at the /spec/data directory.

**Comment by sdj0** [comment]
@mreddy614 this was mostly meant to be run as a binary, so because of the way the modules are arranged you'll need to access `run` from `fire.translator.translator` (admittedly awkward). Here's an example:

```
(firedemo) MacBook-Pro-2:fire-1099 sjohnson$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fire.translator.translator import run
>>> run("./spec/data/valid_all_MISC.json", "outputsample.ascii")
>>> 

(firedemo) MacBook-Pro-2:fire-1099 sjohnson$ cat outputsample.ascii 
T201712345678955AA5TXASDF GLOBAL INCASDF GLOBAL INC123 ASDF STREETNEW YORKNY1000100000002RONALD SWANSON5555555555ronald@swanson.com000000011GSG CORP1234 POIU StTAXVILLETX10991BLERD FLERPLERMERD55577766661A20171123456789ASDF1A123456789ABCDEFG1ASDF GLOBAL INC123 ASDF STREETNEW YORKNY10001555555555500000002B2017SPAC1987654321000000000100000000000200000000000300000000000400000000000500000000000600000000000700000000000800000000000900000000001000000000001100000000001200000000001300000000001400000000001500000000001600000000000000000000000000SPACELEY SPROCKETS5678 INDUSTRY PLACEMOONCA2222200000003B2017BOBL1098765432000000001600000000001500000000001400000000001300000000001200000000001100000000001000000000000900000000000800000000000700000000000600000000000500000000000400000000000300000000000200000000000100000000000000000000000000BOB LOBLAW LLP100 LAWBOMB RDBLOBVILLECA1111100000004C0000000200000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000000000000000000000000000000005F000000010000000000000000000000000000200000006(firedemo) MacBook-Pro-2:fire-1099 sjohnson$ 
```

**Comment by sdj0** [comment]
@brelkl it would be super helpful if you can take a look at the schemas and data files! I'm still able to run the program successfully on the data in /spec/data, but at a glance the schema and test files don't include the new "H" and "J" rows you added in https://github.com/sdj0/fire-1099/pull/18.

**Comment by brelkl** [comment]
Yes, I will try to get to updating the schemas this week, and will keep you posted.
