### ISSUE TITLE
How to run unit tests isn't obvious?  

### ISSUE THREAD

**Issue by castorf** [sdj0/fire-1099#25]
If it wasn't too hard, I thought it'd be nice to generate K records, but it's not obvious to me how to run the tests in the 'spec' directory.

python setup.py tests

doesn't seem to do the trick.

Maybe IRIS will deploy soon and make all this moot.

**Comment by castorf** [comment]
I ran nosetests spec/test*.py and I found a few issues so far:

- spec/data/valid_all_MISC.json is probably referred to in the tests as spec/data/vliad_all.json  [so nothing runs]
- after fixing that: (voting) castor@seneca fire-1099 % nosetests spec/test*
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...............................
======================================================================
FAIL: test_translator.test_translator_insert_payer_totals
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/castor/.conda/envs/voting/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/castor/Documents/tcmvla22/irs/fire-1099/spec/test_translator.py", line 97, in test_translator_insert_payer_totals
    assert len(values) == 16
AssertionError
